/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardMateriaPrimaRouteImport } from './routes/dashboard-materia-prima'
import { Route as DashboardProdutividadeRouteImport } from './routes/dashboard-produtividade'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FinanceiroEvolucaoMensalRouteImport } from './routes/financeiro-evolucao-mensal'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MateriaPrimaRouteImport } from './routes/materia-prima'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMateriaPrimaRoute = DashboardMateriaPrimaRouteImport.update({
  id: '/dashboard-materia-prima',
  path: '/dashboard-materia-prima',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProdutividadeRoute = DashboardProdutividadeRouteImport.update({
  id: '/dashboard-produtividade',
  path: '/dashboard-produtividade',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroEvolucaoMensalRoute =
  FinanceiroEvolucaoMensalRouteImport.update({
    id: '/financeiro-evolucao-mensal',
    path: '/financeiro-evolucao-mensal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaPrimaRoute = MateriaPrimaRouteImport.update({
  id: '/materia-prima',
  path: '/materia-prima',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-materia-prima': typeof DashboardMateriaPrimaRoute
  '/dashboard-produtividade': typeof DashboardProdutividadeRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-evolucao-mensal': typeof FinanceiroEvolucaoMensalRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/materia-prima': typeof MateriaPrimaRoute
  '/pedidos': typeof PedidosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-materia-prima': typeof DashboardMateriaPrimaRoute
  '/dashboard-produtividade': typeof DashboardProdutividadeRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-evolucao-mensal': typeof FinanceiroEvolucaoMensalRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/materia-prima': typeof MateriaPrimaRoute
  '/pedidos': typeof PedidosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-materia-prima': typeof DashboardMateriaPrimaRoute
  '/dashboard-produtividade': typeof DashboardProdutividadeRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-evolucao-mensal': typeof FinanceiroEvolucaoMensalRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/materia-prima': typeof MateriaPrimaRoute
  '/pedidos': typeof PedidosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/cadastro'
    | '/dashboard'
    | '/dashboard-materia-prima'
    | '/dashboard-produtividade'
    | '/definir-senha'
    | '/financeiro'
    | '/financeiro-evolucao-mensal'
    | '/importar'
    | '/login'
    | '/materia-prima'
    | '/pedidos'
    | '/relatorios'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/cadastro'
    | '/dashboard'
    | '/dashboard-materia-prima'
    | '/dashboard-produtividade'
    | '/definir-senha'
    | '/financeiro'
    | '/financeiro-evolucao-mensal'
    | '/importar'
    | '/login'
    | '/materia-prima'
    | '/pedidos'
    | '/relatorios'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/cadastro'
    | '/dashboard'
    | '/dashboard-materia-prima'
    | '/dashboard-produtividade'
    | '/definir-senha'
    | '/financeiro'
    | '/financeiro-evolucao-mensal'
    | '/importar'
    | '/login'
    | '/materia-prima'
    | '/pedidos'
    | '/relatorios'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  DashboardMateriaPrimaRoute: typeof DashboardMateriaPrimaRoute
  DashboardProdutividadeRoute: typeof DashboardProdutividadeRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FinanceiroEvolucaoMensalRoute: typeof FinanceiroEvolucaoMensalRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
  MateriaPrimaRoute: typeof MateriaPrimaRoute
  PedidosRoute: typeof PedidosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-materia-prima': {
      id: '/dashboard-materia-prima'
      path: '/dashboard-materia-prima'
      fullPath: '/dashboard-materia-prima'
      preLoaderRoute: typeof DashboardMateriaPrimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-produtividade': {
      id: '/dashboard-produtividade'
      path: '/dashboard-produtividade'
      fullPath: '/dashboard-produtividade'
      preLoaderRoute: typeof DashboardProdutividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro-evolucao-mensal': {
      id: '/financeiro-evolucao-mensal'
      path: '/financeiro-evolucao-mensal'
      fullPath: '/financeiro-evolucao-mensal'
      preLoaderRoute: typeof FinanceiroEvolucaoMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia-prima': {
      id: '/materia-prima'
      path: '/materia-prima'
      fullPath: '/materia-prima'
      preLoaderRoute: typeof MateriaPrimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  DashboardMateriaPrimaRoute: DashboardMateriaPrimaRoute,
  DashboardProdutividadeRoute: DashboardProdutividadeRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  FinanceiroRoute: FinanceiroRoute,
  FinanceiroEvolucaoMensalRoute: FinanceiroEvolucaoMensalRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
  MateriaPrimaRoute: MateriaPrimaRoute,
  PedidosRoute: PedidosRoute,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
